trigger:
- main
- feature/*

variables:
  subscription: terraform-production
  resourceGroup: static-web-terraform
  storageAccount: staccterraformresume
  container: tfstatefiles-iac
  tfstateFile: iac-base.tfstate

stages:
  - stage: Validate
    jobs:
      - job: Validate
        continueOnError: false
        pool: Default
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Artifacts
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/terraform'
              artifact: 'terraform-out'
              publishLocation: 'pipeline'
          
          - task: TerraformInstaller@1
            displayName: Terraform Install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'terraform-production'
              backendAzureRmResourceGroupName: 'static-web-terraform'
              backendAzureRmStorageAccountName: 'staccterraformresume'
              backendAzureRmContainerName: 'tfstatefiles-iac'
              backendAzureRmKey: 'iac-base.tfstate'
         